version: '3'

services:

  wamp:
    image: nanoserver/wamp:latest
    ports:
      - 1234:80
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html
    restart: always
    networks:
      - learn-php

volumes:
  wp_data: {}

networks:
  learn-php:
